# Generated by Django 3.1 on 2020-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('short_desc', models.CharField(max_length=200, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('main_file', models.FileField(upload_to='media/music/')),
                ('thumbnail_img', models.ImageField(upload_to='media/thumbnail/')),
                ('bgrnd_vid', models.FileField(upload_to='media/bgrnd_video/')),
            ],
        ),
    ]
