# Generated by Django 3.1 on 2020-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(to='music.Genre'),
        ),
    ]
